version: '2'
services:
  node:
    build: ./node
    environment:
      - VIRTUAL_HOST="*"
      - VIRTUAL_HOST_WEIGHT=0

  nginx:
    image: nginx:1.10-alpine
    links:
      - php-fpm
    depends_on:
      - php-fpm
    volumes:
      - ./nginx/vhosts:/etc/nginx/conf.d
      - ./php-fpm/laravel:/srv/laravel
    environment:
      - VIRTUAL_HOST=api.myapp.com, static.myapp.com
      - VIRTUAL_HOST_WEIGHT=1

  php-fpm:
    restart: always
    build: ./php-fpm
    volumes:
      - ./php-fpm/laravel:/srv/laravel
      - ./log/php-fpm:/var/log/php-fpm
    links:
      - postgres
      - redis
    expose:
      - "9000"

  postgres:
    image: postgres:latest
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=secretpass
      - POSTGRES_USER=someuser
      - POSTGRES_DB=somedb
    volumes:
      - ./dump:/dump
      - ./data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    expose:
      - "6379"

  lb:
    image: dockercloud/haproxy
    depends_on:
      - node
      - nginx
    environment:
      - ADDITIONAL_SERVICES=docker:node,docker:nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
